POST http://localhost:8080/payments
Content-Type: application/json

{
  "correlationId": "dc52c78d-e9c6-4f49-9f4f-0e2c63c5ba8a",
  "amount": 10.00
}
###

GET http://localhost:9999/payments-summary
###

GET http://localhost:8001/admin/payments-summary
X-Rinha-Token: 123
###

GET http://localhost:8002/admin/payments-summary
X-Rinha-Token: 123
###

GET http://localhost:8080/payments-summary?from=2025-07-14T22:35:36.294Z&to=2025-07-14T22:35:46.194Z
###

#-- 5775
#-- 8352

#    const inconsistencies =
#Math.abs(
#150205.2 -
#150205.2,
#) +
#Math.abs(
# 130643.5-
#151478.8 ,
#);